# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florian Biermann
email: fbie@itu.dk
description: > # this means to ignore newlines until "baseurl:"
 Hi, my name is Florian, I am a PhD student at the IT University of
 Copenhagen. My project focuses on parallel and functional programming
 in spreadsheets as part of the Popular Parallel Programming
 project. I am fundet by the Sino-Danish Center for Education and
 Research.
baseurl: "people/fbie" # the subpath of your site, e.g. /blog
url: "http://itu.dk" # the base hostname & protocol for your site
twitter_username: florianbier
github_username:  fbie

# Build settings
markdown: kramdown
