# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florian's Blog
email: fbie@itu.dk
description: > # this means to ignore newlines until "baseurl:"
 Hi, my name is Florian "罗恩" Biermann, I am a PhD student at the IT
 University of Copenhagen and I work on parallel and functional
 programming in spreadsheets. This blog is about my project,
 programming, China, Emacs and food.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "http://itu.dk/people/fbie" # the base hostname & protocol for your site
twitter_username: florianbier
github_username:  fbie

# Build settings
markdown: kramdown
